name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Installing Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create report directory
      run: mkdir -p reports/pytest

    - name: Running tests
      run: pytest --html=reports/pytest/report.html --self-contained-html

    - name: Check PEP8 compliance with flake8
      run: flake8 . --max-line-length=200

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: reports/pytest/report.html